### ISSUE TITLE
The add recipe endpoint for the forkify project is returning a 500 status code

### ISSUE THREAD

**Issue by Walexero** [jonasschmedtmann/complete-javascript-course#381]
I'm not able to implement the add recipe functionality because of the endpoint returning an error code. Is there a way to have this fixed anytime soon?

**Comment by j-koziel** [comment]
I quickly tested this in [Postman ](https://www.postman.com/) (lets you quickly test an api) and I received the below result. As you can see it succeeded with my test data. I think that the API is in fact working.
![image](https://github.com/jonasschmedtmann/complete-javascript-course/assets/68497216/94433187-1d91-4759-b9d6-b53b5b7a38e7)

Below you can see the same error message that you were getting before but with a GET request instead of a POST request. This is probably why you were getting this message if you were testing this endpoint in the browser.
![image](https://github.com/jonasschmedtmann/complete-javascript-course/assets/68497216/2b21c892-03bb-471f-8222-6d4ba5199a06)

**Comment by Walexero** [comment]
I have it fixed, it was more an issue in the code than the api
