### ISSUE TITLE
PLEASE HELP! "console was used before it was defined"

### ISSUE THREAD

**Issue by ChickenGunner** [jonasschmedtmann/complete-javascript-course#40]
I keep getting these errors and I cannot input anything into the console! PLEASE HELP ASAP!
![Desktop_190930_1354](https://user-images.githubusercontent.com/55789427/65872749-f875b880-e389-11e9-82fb-a7e70306e940.png)
![Desktop_190930_1354_1](https://user-images.githubusercontent.com/55789427/65872751-f90e4f00-e389-11e9-8bc5-18539f45c2db.png)
![Desktop_190930_1355](https://user-images.githubusercontent.com/55789427/65872752-fa3f7c00-e389-11e9-9887-2750a1606256.png)

**Comment by jonasschmedtmann** [comment]
As I mentioned many times in the course Q&A, **this is not an error**. Nothing will stop working because of this. It is simply a problem with ESLint in Brackets (ESLint is a program that checks for coding mistakes, but this is currently not working properly in Brackets).
So if your code doesn't work, it is not because of this warning that ESLint shows you. A told you that in another issue already some days ago, so why do you keep posting this?
Actually, **I already gave you the solution to this one last week**! It's happening because the script.js file is not in the correct folder. Of course, it has to be in the same folder as index.html, so in the starter folder.

**Comment by ChickenGunner** [comment]
OK thanks

**Comment by jonasschmedtmann** [comment]
This time, please let me know if this works ;)

**Comment by ChickenGunner** [comment]
Ok thank you!

**Comment by cosmonautica** [comment]
Sorry but how do I unsubscribe from all the emails? And for all new threads? Thanks
