### ISSUE TITLE
food2fork

### ISSUE THREAD

**Issue by chintankamani** [jonasschmedtmann/complete-javascript-course#45]
I think the food2fork site is down, I am unable to login into the site and receive the api key to continue with the course.

**Comment by jonasschmedtmann** [comment]
The food2fork API does sometimes fail, that's true. That's why we created an alternative API that works almost in the exact same way. Please refer to [Lecture 139](https://www.udemy.com/course/the-complete-javascript-course/learn/lecture/16668826#overview) on Udemy.

**Comment by gaurav-js-dev** [comment]
https://spoonacular.com/food-api seems a great alternative and everything works the same way. @jonasschmedtmann  May I know the alternative API you have impletemented ?

**Comment by jonasschmedtmann** [comment]
As I said above, it's at lecture 139 of the course.z

**Comment by Parsa-Sedigh** [comment]
Hey Jonas, I don't have access to Lecture 139 . Can you name the alternative API or solution to food2fork?Because it has been shut down!!

**Comment by SvilenGrandzhan** [comment]
Hey, Parsa
Did you check this as solution: 
"020: Build Real Projects!
Your progress
PLEASE READ: Changes to the Project API

👉 In the next lecture, I will introduce the food2fork API, which I use to build the project in this section.

However, as of November 30th, this API unfortunately no longer works. I decided to build my own API based on the food2fork API, which is simply called forkify-api.

This is the API that you should use to build the project in this section (I use the original food2fork API in the videos). Don't worry, everything will work almost exactly as in the videos!

So, most of the information in the next video is still relevant because the forkify-api works almost exactly as food2fork, so please just follow the next video, and of course the rest of the project.


👉 Here are the 3 things that you need to know about forkify-api which are DIFFERENT from the food2fork API in the videos:

1) No API key is required;

2) No proxy is required;

3) The URL is forkify-api.herokuapp.com (click for basic documentation).


👉 This is how you use forkify-api instead of the food2fork API.

In the Search.js file (as soon as you get there), just replace:

    const res = await axios(`${PROXY}http://food2fork.com/api/search?key=${KEY}&q=${this.query}`);

with this:

    const res = await axios(`https://forkify-api.herokuapp.com/api/search?&q=${this.query}`);


Then, in Recipe.js (as soon as you get there), please replace:

    const res = await axios(`${PROXY}http://food2fork.com/api/get?key=${KEY}&rId=${this.id}`);

with this:

    const res = await axios(`https://forkify-api.herokuapp.com/api/get?rId=${this.id}`);


👉 That's it, that's all you need to know. Again, make these changes as you go through the projects. For now, just keep following the videos. And now, have fun with the project "

**Comment by bientehaa** [comment]
> Hey Jonas, I don't have access to Lecture 139 . Can you name the alternative API or solution to food2fork?Because it has been shut down!!

The config is as bellow: 

import axios from 'axios'

```

async function getResult(query) {
  const proxy = 'https://cors-anywhere.herokuapp.com/'
  try {
    const res = await axios(`https://forkify-api.herokuapp.com/api/search?q=${query}`)
    const recipes = res.data.recipes
    console.log(recipes)
  } catch(error) {
    alert(error)
  }
}
getResult('pizza') 
```

**Comment by nnmmaa1234** [comment]
Hi
I have followed all instructions as stated in the course, in lecture-14 of section-9 (Building Search View Pt.1), whenever I search for a query, I first get an alert saying "**_ReferenceError: recipes is not defined_**" and only after clicking "ok", I see my results in the console.
Does this have to do with something relating to the changes in API (have others also faced this problem?). I can't seem to figure out the root of this, because only in our src/Seach.js file we output our recipes in the console.
Here's the code I'm my Search.js file:
`
import axios from 'axios';

export default class Search {
    constructor(query) {
        this.query = query;
    };

    async getResults(query){
        try {
            const res = await axios(`https://forkify-api.herokuapp.com/api/search?&q=${this.query}`);
            this.result = res.data.recipes;
            console.log(recipes);
        } catch(error) {
            alert(error);
        }   
    }
}
`
I'm just concerned that howcome... even though it first shows the error, saying "recipes" is not defined, then also shows the recipes afterwards?

**Comment by RefinedSilver** [comment]
Hi Jonas,
I am at a complete loss as to how to obtain the forkify API key from your Udemy course; the one that originally had food2fork's API. I am very new, so there's a chance that I might not be super-knowledgeable about locating API keys. What are the steps?

**Comment by Prithwidipta** [comment]
I don't understand what do you mean?
